version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/zachkarp33/Game/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
          version: 2.1
          
          jobs:
            build:
              docker:
                - image: circleci/python:3.8  # Use an appropriate Python version
              steps:
                - checkout  # Checkout your source code (assuming it's in a Git repository)
                - run:
                    name: Install Dependencies
                    command: |
                      pip install -r requirements.txt  # If you have any dependencies
                - run:
                    name: Run Guess the Number Game
                    command: |
                      python guess_the_number.py  # Replace with the actual name of your Python file
          
          workflows:
            version: 2
            build-deploy:
              jobs:
                - build
          

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
    